"""empty message

Revision ID: 4280ccbad0dc
Revises: f3c960dc5f35
Create Date: 2017-11-27 22:55:16.945452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4280ccbad0dc'
down_revision = 'f3c960dc5f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'content',
               existing_type=mysql.VARCHAR(length=4096),
               nullable=True)
    op.add_column('users', sa.Column('email', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.alter_column('comments', 'content',
               existing_type=mysql.VARCHAR(length=4096),
               nullable=False)
    # ### end Alembic commands ###
