"""empty message

Revision ID: 456ac79dab11
Revises: 
Create Date: 2017-11-27 20:59:29.986845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456ac79dab11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=4096), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
